########## Cria um novo usuário
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Henrique Matheus",
  "email": "henrique@email.com",
  "password": "123"
}
########## Cria um novo usuário
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Robson Santos",
  "email": "robson@email.com",
  "password": "123"
}
########## Cria um novo usuário
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Kamila Tanizaka",
  "email": "kamila@email.com",
  "password": "123"
}

####### Logar usuários
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "henrique@email.com",
  "password": "123"
}

############### users ################
##### Buscar todos os usuários #####
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IkNhcmxvcyBEYW5pZWwiLCJlbWFpbCI6ImRhbmllbDFAZW1haWwuY29tIiwicm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpYXQiOjE3NDY1ODMwNDYsImV4cCI6MTc0NjU4NDg0Nn0.zslkLciHTkPIg8hkTpVQ-t4cy9S6kJJhzEzxn2ULQbs

##### Buscar um usuário pelo ID #####
GET http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkNhcmxvcyBEYW5pZWwgSm92ZWxpbm8gUGVyZWlyYSBEb3MgU2FudG9zIiwiZW1haWwiOiJjYXJsb3NAZW1haWwuY29tIiwicm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpYXQiOjE3NDY1ODUxNjMsImV4cCI6MTc0NjU4Njk2M30.KTtc0878vfOsGlX7HVkhnj0xvrEUjeO3ZI1Vrx3eUXE
